mqtt:
  client:
    protocol: 4      # MQTTv311
  connection:
    host: 192.168.1.161
    port: 1883
    keepalive: 60
bridge:
  # Positions
  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: geometry_msgs.msg:PoseWithCovarianceStamped
    topic_from: /gtec/ekf/position/6a39
    topic_to: /gtec/ekf/position/6a39
  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: visualization_msgs.msg:MarkerArray
    topic_from: /gtec/toa/anchors
    topic_to: /gtec/toa/anchors
  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: gtec_msgs.msg:Ranging
    topic_from: /gtec/uwb/ranging/pozyx
    topic_to: /gtec/uwb/ranging/pozyx

